Update main_thamco.yml

diff --git a/.github/workflows/main_thamco.yml b/.github/workflows/main_thamco.yml
--- a/.github/workflows/main_thamco.yml
+++ b/.github/workflows/main_thamco.yml
@@ -1,4 +1,4 @@
-name: Build and deploy ASP.Net Core app to Azure Web App - thamco
+name: Build, Test, and Deploy ASP.Net Core app to Azure Web App - thamco
 
 on:
   push:
@@ -7,11 +7,12 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-and-test:
+  build:
     runs-on: windows-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
       - name: Set up .NET Core
         uses: actions/setup-dotnet@v1
@@ -22,14 +23,45 @@ jobs:
       - name: Build with dotnet
         run: dotnet build --configuration Release
 
-      - name: dotnet test
-        run: dotnet test --configuration Release --no-restore --verbosity normal
-        id: test
-        continue-on-error: true
+      - name: dotnet publish
+        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
+
+      - name: Upload artifact for deployment job
+        uses: actions/upload-artifact@v2
+        with:
+          name: .net-app
+          path: ${{env.DOTNET_ROOT}}/myapp
+
+  test:
+    runs-on: windows-latest
+    needs: build
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up .NET Core
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.x'
+          include-prerelease: true
+
+      - name: Restore dependencies
+        run: dotnet restore
+
+      - name: Build and run tests
+        run: |
+          dotnet test --configuration Release --no-restore --verbosity normal
+          test_result=$?
+
+          if [ ${{ needs.build-and-test.outputs.test.result }} != 0 ]; then
+            echo "Tests failed. Skipping deployment."
+            exit ${{ needs.build-and-test.outputs.test.result }}
+          fi
 
   deploy:
-    needs: build-and-test
     runs-on: windows-latest
+    needs: [build, test]
     environment:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
@@ -40,13 +72,6 @@ jobs:
         with:
           name: .net-app
 
-      - name: Check test result
-        run: |
-          if [ ${{ needs.build-and-test.outputs.test.result }} -ne 0 ]; then
-            echo "Tests failed. Skipping deployment."
-            exit ${{ needs.build-and-test.outputs.test.result }}
-          fi
-
       - name: Deploy to Azure Web App
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v2
@@ -55,3 +80,4 @@ jobs:
           slot-name: 'Production'
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4CECDC469E8240FCA7D0F046672CA053 }}
           package: .
+
